Web/Controllers/ClassifiersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Core.Model;
using Data;
using Service;
using AutoMapper;
using Web.ViewModel;

namespace Web.Controllers
{
    public class ClassifiersController : Controller
    {
        private IAirportService _airportService;
        private IAirportSchemeService _airportSchemeService;
        private ICityService _cityService;
        private ICountryService _countryService;
        private IGateService _gateService;
        private IFlightService _flightService;
        private IPlaneService _planeService;
        private ITerminalService _terminalService;
        private ITimeTableService _timeTableService;

        public ClassifiersController(IAirportService airportService, IAirportSchemeService airportSchemeService, 
            ICityService cityService, ICountryService countryService, IGateService gateService, IFlightService flightService, 
            IPlaneService planeService, ITerminalService terminalService, ITimeTableService timeTableService)
        {
            _airportService = airportService;
            _airportSchemeService = airportSchemeService;
            _cityService = cityService;
            _countryService = countryService;
            _gateService = gateService;
            _flightService = flightService;
            _planeService = planeService;
            _terminalService = terminalService;
            _timeTableService = timeTableService;
        }


        // GET: Empty view
        public ActionResult Index()
        {
            return View();
        }

        // GET: Airports
        public ActionResult AirportIndex(int pageNumber = 1)
        {
            int pageSize = 10;
            ViewData["PageNumber"] = pageNumber;

            IEnumerable<AirportViewModel> airports = Mapper.Map<IEnumerable<Airport>, IEnumerable<AirportViewModel>>(_airportService.GetAirports(pageNumber, pageSize, out var totalPages));

            ViewData["TotalPages"] = totalPages;

            return PartialView(airports);
        }

        //GET: airports names for autocomplete search
        public ActionResult AirportSearch(string term)
        {
            //send airport collection and work with it, get names from it and use values from it
            //IEnumerable<AirportViewModel> airports = Mapper.Map<IEnumerable<Airport>, IEnumerable<AirportViewModel>>(_airportService.GetAirports(term));
            //add in json id and pass it like a dictionary id - name, then open pass id in edit method if something were choosen in autocomplete field.
            return Json(_airportService.GetAirportNames(term), JsonRequestBehavior.AllowGet);
        }

        public RedirectToRouteResult AirportGetIdByName(string name)
        {
            //var value = searchBox.Value;
            var airportId = _airportService.GetAirportIdByName(name);
            if (airportId > 0)
            {
                return RedirectToAction("AirportEditFull", new { id = airportId });
            }
            else
            {
                return RedirectToAction("AirportIndexFull");
            }
        }

        public ActionResult AirportIndexFull(int pageNumber = 1)
        {
            int pageSize = 10;
            ViewData["PageNumber"] = pageNumber;

            IEnumerable<AirportViewModel> airports = Mapper.Map<IEnumerable<Airport>, IEnumerable<AirportViewModel>>(_airportService.GetAirports(pageNumber, pageSize, out var totalPages));

            ViewData["TotalPages"] = totalPages;
            return View("AirportIndex", airports);
        }

        // GET: Airports/Create
        public ActionResult AirportCreate()
        {
            AirportViewModel airport = new AirportViewModel();
            airport.Cities = _cityService.GetCities();
            return PartialView(airport);
        }

        // POST: Airports/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AirportCreate([Bind(Include = "Id,Name,Code,CityId")] AirportViewModel airport)
        {
            if (ModelState.IsValid)
            {
                airport.City = _cityService.GetCity(airport.CityId);
                _airportService.CreateAirport(Mapper.Map<AirportViewModel, Airport>(airport));
                return RedirectToAction("AirportIndexFull");
            }

            airport.Cities = _cityService.GetCities();
            return View(airport);
        }
        
        // GET: Airports/Edit/5
        public ActionResult AirportEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirportViewModel airport = Mapper.Map<Airport, AirportViewModel>(_airportService.GetAirport((int)id));
            if (airport == null)
            {
                return HttpNotFound();
            }
            airport.Cities = _cityService.GetCities();
            return PartialView(airport);
        }

        public ActionResult AirportEditFull(int id)
        {
            AirportViewModel airport = Mapper.Map<Airport, AirportViewModel>(_airportService.GetAirport(id));
            if (airport == null)
            {
                return HttpNotFound();
            }
            airport.Cities = _cityService.GetCities();
            return View("AirportEdit", airport);
        }

        // POST: Airports/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AirportEdit([Bind(Include = "Id,Name,Code,CityId")] AirportViewModel airport)
        {
            if (ModelState.IsValid)
            {
                _airportService.UpdateAirport(Mapper.Map<AirportViewModel, Airport>(airport));
                return RedirectToAction("AirportIndexFull");
            }
            return PartialView(airport);
        }
        
        // GET: Airports/Delete/5
        public ActionResult AirportDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirportViewModel airport = Mapper.Map<Airport, AirportViewModel>(_airportService.GetAirport((int)id));
            if (airport == null)
            {
                return HttpNotFound();
            }
            return PartialView(airport);
        }

        // POST: Airports/DeleteConfirm/5
        [HttpPost, ActionName("AirportDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult AirportDeleteConfirmed(int id)
        {
            _airportService.DeleteAirport(id);
            return RedirectToAction("AirportIndexFull");
        }

        // GET: Airports
        public ActionResult TerminalIndex()
        {
            IEnumerable<TerminalViewModel> terminals = Mapper.Map<IEnumerable<Terminal>, IEnumerable<TerminalViewModel>>(_terminalService.GetTerminals());
            return PartialView(terminals);
        }
    }
}

Web/Views/Classifiers/AirportCreate.cshtml
@using Web.ViewModel
@model AirportViewModel

@{
    ViewBag.Title = "Create airport";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_SideBar")
        </div>
        <div class="col-md-10" id="bodycontent">
            <div class="row">
                <div class="col-md-12">
                    <h3>Create new airport</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(m => m.CityId, new SelectList(Model.Cities, "Id", "Name"), "Please select an option", new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-success" />
                                    @Ajax.ActionLink("Cancel", "AirportIndex", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "btn btn-default" })
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Classifiers/AirportDelete.cshtml
@using Web.ViewModel
@model AirportViewModel

@{
    ViewBag.Title = "Delete " + @Model.Name;
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_SideBar")
        </div>
        <div class="col-md-10" id="bodycontent">
            <div class="row">
                <div class="alert alert-danger col-md-3 deleteAlertText">
                    <h4 class="deleteAlertText">Are you sure you want to delete this?</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <h4>@Model.Name airport</h4>
                    <hr />
                </div>
            </div>
            <div class="row">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <div class="col-md-offset-0 col-md-10">
                            <input type="submit" value="Confirm" class="btn btn-danger" />
                            @Ajax.ActionLink("Cancel", "AirportEdit", "Classifiers", new { id = Model.Id }, new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "btn btn-default" })
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Web/Views/Classifiers/AirportEdit.cshtml
@using Core.Model
@using Web.ViewModel
@model AirportViewModel

@{
    ViewBag.Title = "Edit " + @Model.Name;
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_SideBar")
        </div>
        <div class="col-md-10" id="bodycontent">
            <div class="row">
                <div class="col-md-12"><h3>Edit @Model.Name airport</h3></div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="dropdown col-md-10">
                                    @Html.DropDownListFor(m => m.CityId, new SelectList(Model.Cities, "Id", "Name"), new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-success" />
                                    @Ajax.ActionLink("Cancel", "AirportIndex", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "btn btn-default" })
                                    @Ajax.ActionLink("Delete", "AirportDelete", "Classifiers", new { id = Model.Id }, new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "btn btn-danger" })
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Web/Views/Classifiers/AirportIndex.cshtml
@using Web.ViewModel
@model IEnumerable<AirportViewModel>

@{
    ViewBag.Title = "Airports";
}

@Scripts.Render("~/Scripts/jquery-ui")
@Styles.Render("~/Content/jquery-ui")

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_SideBar")
        </div>
        <div class="col-md-10" id="bodycontent">
            <div class="row">
                <div class="col-md-12">
                    <h2>Airports</h2>
                </div>
            </div>
            <div class="row createButton">
                <div class="col-md-12">
                    @Ajax.ActionLink("Create new", "AirportCreate", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class="btn btn-default" })
                </div>
            </div>
            <div class="row createButton">
                <div class="col-md-2">
                    <input type="text" name="name" class="form-control" runat="server" id="searchBox" data-autocomplete-source='@Url.Action("AirportSearch", "Classifiers")' />
                </div>
                <div class="col-md-2">
                    @*pass name from data-autocomplete-source to parameter*@
                    <input type="button" class="btn btn-default" value="Search" onclick="location.href = '@Url.Action("AirportGetIdByName", new {name = "Vnukovo"})'"/>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-hover" id="linkedtable">
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Name)</th>
                            <th>@Html.DisplayNameFor(model => model.Code)</th>
                            <th>@Html.DisplayNameFor(model => model.City)</th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr onclick="this.children[0].children[0].click();">
                                <td class="linkedTableText">
                                    @Ajax.ActionLink(item.Name, "AirportEdit", "Classifiers", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "bodycontent" }, new{ style="display:none;" })
                                    @item.Name
                                </td>
                                <td class="linkedTableText">
                                    @Html.DisplayFor(modelItem => item.Code)
                                </td>
                                <td class="linkedTableText">
                                    @Html.DisplayFor(modelItem => item.City.Name)
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    @{
                        var totalPages = int.Parse(ViewData["TotalPages"].ToString());
                        var currentPage = int.Parse(ViewData["PageNumber"].ToString());
                    }
                    
                    @if (totalPages < 6)
                    {
                    <ul class="pagination justify-content-center">
                        @if (currentPage == 1)
                        {
                            <li class="page-item disabled"><a class="page-link">Previous</a></li>
                        }
                        else
                        {
                            <li>@Ajax.ActionLink("Previous", "AirportIndex", "Classifiers", new {pageNumber = currentPage - 1}, new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "page-item" })</li>
                        }

                        @for (int i = 1; i <= totalPages; i++)
                        {
                            <li>@Ajax.ActionLink(i.ToString(), "AirportIndex", "Classifiers", new {pageNumber = i}, new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "page-item" })</li>
                        }

                        @if (currentPage == totalPages)
                        {
                            <li class="page-item disabled"><a class="page-link">Next</a></li>
                        }
                        else
                        {
                            <li>@Ajax.ActionLink("Next", "AirportIndex", "Classifiers", new {pageNumber = currentPage + 1}, new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "page-item" })</li>
                        }
                    </ul>
                    }
                    else
                    {
                    <ul class="pagination">
                        <li>@Ajax.ActionLink("First", "AirportIndex", "Classifiers", new { pageNumber = 1 }, new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "page-item" })</li>
                        <li>@Ajax.ActionLink("Pervious", "AirportIndex", "Classifiers", new { pageNumber = currentPage - 1 }, new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "page-item" })</li>
                        <li class="page-item disabled"><a class="page-link">@currentPage</a></li>
                        <li>@Ajax.ActionLink("Next", "AirportIndex", "Classifiers", new { pageNumber = currentPage + 1 }, new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "page-item" })</li>
                        <li>@Ajax.ActionLink("Last", "AirportIndex", "Classifiers", new { pageNumber = totalPages }, new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "page-item" })</li>
                    </ul>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@*script get names from controllers method*@
<script>
    $(function () {
        $("[data-autocomplete-source]").each(function () {
            var target = $(this);
            target.autocomplete({ source: target.attr("data-autocomplete-source") });
        });
    });
</script>

Web/Views/Classifiers/Create.cshtml
@using Core.Model
@model Core.Model.Airport

@{
    ViewBag.Title = "Create";
}

@{
    IEnumerable<Terminal> terminals = (IEnumerable<Terminal>)ViewData["Terminals"];
    IEnumerable<Gate> gates = (IEnumerable<Gate>)ViewData["Gates"];
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Airport</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

    <div class="form-horizontal">
        <hr />
        <h4>Terminals</h4>
        <hr />
        @foreach (Terminal terminal in terminals)
        {
            <div>
                <input type="checkbox" value="@terminal.Id" name="@terminal.Name" class="checkbox"/>@terminal.Name
                <div>
                    <p>Gates of terminal @terminal.Name</p>
                    @foreach (Gate gate in gates)
                    {
                        <div>
                            @Html.CheckBox(@gate.Name, false)
                            @*<input type="checkbox" value="@gate.Id" name="@gate.Name" class="checkbox"/>@gate.Name*@
                        </div>
                    }
                </div>
            </div>
        }


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Classifiers/Delete.cshtml
@model Core.Model.Airport

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Airport</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web/Views/Classifiers/Edit.cshtml
@model Core.Model.Airport

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Airport</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Classifiers/Index.cshtml
@{
    ViewBag.Title = "Classifiers";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_SideBar")
        </div>
        <div class="col-md-10">
            <div class="alert alert-info" id="classifiersindexpage">
                <p class="classifiersIndexText">Choose classifier in left handed menu.</p>
            </div>
        </div>
    </div>
</div>

Web/Views/Classifiers/TerminalIndex.cshtml
@using Web.ViewModel
@model IEnumerable<TerminalViewModel>

@{
    ViewBag.Title = "Terminals";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_SideBar")
        </div>
        <div class="col-md-10" id="bodycontent">
            <div class="row">
                <h2>Terminals</h2>
            </div>
            <div class="row">
                <input type="button" class="btn btn-default" value="Create new" onclick="location.href = '@Url.Action("AirportCreate", "Classifiers")'" />
                <p />
            </div>
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-hover" id="linkedtable">
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Name)</th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="linkedTableText" onclick="location.href = '@Url.Action("AirportEdit", "Classifiers", new {id = item.Id})'">
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Views/Classifiers/_SideBar.cshtml
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
@Styles.Render("~/Content/fa")

 <div class="wrapper">
    <div class="nav-side-menu">
        <div class="menu-list">

            <ul id="menu-content" class="menu-content">

                <li data-toggle="collapse" data-target="#airports" class="collapsed active">
                    <a href="#"><i class="fa fa-houzz fa-lg"></i> Airports <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="airports">
                    <li>@Ajax.ActionLink("Airports", "AirportIndex", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "ajaxSmallLinks" })</li>
                    <li>@Ajax.ActionLink("Airport schemes", "AirportIndex", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "ajaxSmallLinks" })</li>
                    <li>@Ajax.ActionLink("Terminals", "TerminalIndex", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "ajaxSmallLinks" })</li>
                    <li>@Ajax.ActionLink("Gates", "AirportIndex", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "ajaxSmallLinks" })</li>
                </ul>

                <li data-toggle="collapse" data-target="#locations" class="collapsed active">
                    <a href="#"><i class="fa fa-map-marker fa-lg"></i> Locations <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="locations">
                    <li>@Ajax.ActionLink("Cities", "AirportIndex", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "ajaxSmallLinks" })</li>
                    <li>@Ajax.ActionLink("Countries", "AirportIndex", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "ajaxSmallLinks" })</li>
                </ul>

                <li>
                    <a href="#"><i class="fa fa-plane fa-lg"></i>@Ajax.ActionLink("Planes", "AirportIndex", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "ajaxLinks" })</a>
                </li>

                <li>
                    <a href="#"><i class="fa fa-clipboard fa-lg"></i>@Ajax.ActionLink("Flights", "AirportIndex", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "ajaxLinks" })</a>
                </li>

                <li>
                    <a href="#"><i class="fa fa-calendar fa-lg"></i>@Ajax.ActionLink("Time tables", "AirportIndex", "Classifiers", new AjaxOptions { UpdateTargetId = "bodycontent" }, new { @class = "ajaxLinks" })</a>
                </li>
            </ul>
        </div>
    </div>
</div>